### ISSUE TITLE
How to display qrcode?

### ISSUE THREAD

**Issue by ofttryaj** [calum/terminal_image_display#10]
I want to show qrcode in terminal, but the result is not complete:
![image](https://user-images.githubusercontent.com/15887451/56779528-00936000-680e-11e9-8202-602b76cbae3e.png)

**Comment by calum** [comment]
Hi there, sorry I took so long to see this issue! I will take a look at this now.

I'll try playing around with QR codes. Are you trying to view an image file, or are you generating the QR code using a library lik `qrcode-rust`?

**Comment by calum** [comment]
To print a QR code from an image file, you need to make sure the terminal dimensions are at least as large as the qr code dimensions. The terminal width is equal to the total number of characters you can type in a single row. The terminal height is half the total number of rows you can view.

I'm currently working on a QR Code generator for the terminal which I will link here for you to use in the future. The QR code you gave as an example is quite large and possibly too large to fit in a terminal.

**Comment by calum** [comment]
Please see this example for how to print a QR code to a terminal:
https://github.com/calum/terminal_qrcode
```rust
extern crate qr_terminal;

use qr_terminal::TermQrCode;

fn main() {
    let code = TermQrCode::from_bytes(b"Hello, World!");
    code.print();
}
```

Running that example generated the following QR code:
![image](https://user-images.githubusercontent.com/22115035/65802073-80817580-e172-11e9-8e00-0a41a771f14c.png)

**Comment by calum** [comment]
Please re-open this issue if you want to discuss this further.

**Comment by ofttryaj** [comment]
@calum Thank you, I will try it later.
